<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>REG</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a70838d6-fedd-4eca-acc1-b43bd7010c38</testSuiteGuid>
   <testCaseLink>
      <guid>114baa33-5148-43e3-b9d3-2ae72f900b0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RE/RE-usrname_Invalid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd494235-1d5d-431d-9ecc-ecce72fda614</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56419f27-6fa5-4841-ae14-7f4666f23e5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RE/RE-password_invalid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0862a450-eee5-47be-9a83-a024dc1b81d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>324865aa-2c32-4993-833a-f0cb8b9b7a99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RE/RE-password_unmatch</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>829751e2-c2c8-4339-92ce-2cbe3c3fb580</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3cbc9cfe-13f1-40a5-9239-526440a5959c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RE/RE-email_Invalid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>466539fd-ccf8-4df1-81ff-d8b9f5c07340</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8df83401-77e4-4bd9-b48c-896687ab5641</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RE/Register</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b967d0f-927e-432f-88f4-e8246125b061</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
